### ISSUE TITLE
bats tests failing on ci

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-build#136]
https://jenkins.spring.io/view/Spring%20Cloud/view/CI.MASTER/job/spring-cloud-build-master-ci/8897/console

because of env vars on jenkins. Disabling for now.

**Comment by marcingrzejszczak** [comment]
fixed via https://github.com/spring-cloud/spring-cloud-build/commit/cd389e7a3b8144a4f6de123e829b86eabfe773a0
