### ISSUE TITLE
Will spring-cloud-build move to spring-boot 2.3.x?

### ISSUE THREAD

**Issue by elefeint** [spring-cloud/spring-cloud-build#149]
`spring-cloud-build` version of `spring-boot` is [2.2.2.RELEASE](https://github.com/spring-cloud/spring-cloud-build/blob/a579b7fb030e582a1609480dd7b485e6ee87d31d/pom.xml#L31). Are there plans to go forward to `2.3.0.BUILD-SNAPSHOT`?

A semi-related question is: what happens to `spring-cloud-build` version?  My understanding of the versions across projects is this:

|spring-cloud-gcp|spring cloud release train|spring-cloud-build|spring-boot
|---|---|---|---|
|1.2.x|Hoxton|2.2.1|2.2.x and 2.3.x
|1.3.x|Ilford|2.2.2.BUILD-SNAPSHOT|2.4.x

Does `spring-cloud-build` major/minor version for `Illford` need to change? Currently it seems that `Hoxton` release train has nowhere to grow, as `Hoxton` and `Illford` only differ in their patch version.

**Comment by spencergibb** [comment]
Hoxton will eventually go to 2.3.x. We have not branched for Ilford yet. At that time, build will go to 3.0.x since it is a major release.
