### ISSUE TITLE
Add Configuration to attach Source / Javadoc Jars

### ISSUE THREAD

**Issue by kevinconaway** [spring-cloud/spring-cloud-build#15]
Since the projects that inherit from this parent pom are libraries, the source and javadoc artifacts should be published in Maven along with the main artifact.  This enables developers to pull in the sources and documentations via their IDEs to better work with and debug the libraries.

I'm happy to submit a PR for this but its fairly simple to do:
https://maven.apache.org/plugin-developers/cookbook/attach-source-javadoc-artifacts.html

**Comment by spencergibb** [comment]
What aren't you seeing published? My spot check shows they are published. http://search.maven.org/#artifactdetails%7Corg.springframework.cloud%7Cspring-cloud-netflix-core%7C1.0.3.RELEASE%7Cjar

http://search.maven.org/#artifactdetails%7Corg.springframework.cloud%7Cspring-cloud-commons%7C1.0.2.RELEASE%7Cjar

**Comment by kevinconaway** [comment]
You're right, sorry.  I wasn't seeing spring-cloud-commons but it due to a quirk of my environment.

Closing this out
