### ISSUE TITLE
Sources missing from central mvnrepository since RELEASE 2.1.4

### ISSUE THREAD

**Issue by janderssonse** [spring-cloud/spring-cloud-build#156]
**Describe the bug**
Since release 2.1.4, the sources jar is missing from mvncentral. This breaks earlier behaviour for example for any tool expecting to find the sources along with the regular release jar.

**Sample**
In all versions in central mvnrepository up until 2.1.4 the sources jar can be found. see for example 2.1.3
https://repo1.maven.org/maven2/org/springframework/cloud/spring-cloud-starter-openfeign/2.1.3.RELEASE/

In versions after that it is missing, example
https://repo1.maven.org/maven2/org/springframework/cloud/spring-cloud-starter-openfeign/2.2.1.RELEASE/

**Comment by spencergibb** [comment]
Does a pom artifact have sources?

**Comment by spencergibb** [comment]
I don't think this is an issue anymore

**Comment by janderssonse** [comment]
@spencergibb It is still an issue, have a look at https://repo1.maven.org/maven2/org/springframework/cloud/spring-cloud-starter-openfeign/4.1.0/ - A sources jar is expected and the overall standard java maven publishing convention is that the sources jar is also published - see other projects in the ecosystem, examples https://repo1.maven.org/maven2/org/springframework/cloud/spring-cloud-cli/3.1.0/ or even other prominent java projects. https://repo1.maven.org/maven2/org/junit/jupiter/junit-jupiter-engine/5.10.1/ . So, I can't understand the rationales for not doing this here, and can't find anything in the documentation either regarding why this project should choose not to. If no rationale can be found, I would assume it is a bug, and an misconfiguration in the publishing configuration.

**Comment by janderssonse** [comment]
I vote for reopening so at least it will have chance of being fixed

**Comment by spencergibb** [comment]
A starter is a pom and there are no sources

**Comment by janderssonse** [comment]
@spencergibb Yes. you are correct,. sorry my bad :) Looking into the jar, for the versions where it used to be published (pre 2.1.3) it was only containing metadata, poms and as you say no real sources which makes it technically correct to not have that artifact - I agree with you now.

The whole rationale for opening this was:  I used was an source collector tool if i recall,  breaking  the usage  (this was a while ago) when it could not find sources jar to import any longer - but that was cleary a bug in that tool I can conclude then.  Sadly I don't rememeber which tool it was hmm. Anyway, keep this closed. thanks for the quick response and have a nice christmas!
