### ISSUE TITLE
Document enabling of spring profile when opening project

### ISSUE THREAD

**Issue by Turbots** [spring-cloud/spring-cloud-build#159]
When opening one of the Spring Cloud projects in an IDE, not all dependencies will be found. The IDE will complain until you figure out to enable the `spring` Maven profile.
We should document to enable the `spring` profile when developing on Spring Cloud.

**Comment by spencergibb** [comment]
Should be added to this section or a new section right below: https://github.com/spring-cloud/spring-cloud-build/blob/master/docs/src/main/asciidoc/building-base.adoc#working-with-the-code
