### ISSUE TITLE
run bats in docker image

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-build#163]
https://github.com/bats-core/bats-core#running-bats-in-docker

**Comment by marcingrzejszczak** [comment]
If we remove generate_readme and migrate away to docs.spring.io then we won't need any bash scripts.

**Comment by marcingrzejszczak** [comment]
Done via https://github.com/spring-cloud/spring-cloud-build/commit/5682e8d214929a40ed9292699a004c9b190985c6
