### ISSUE TITLE
Hoxton.SR5 BOM inadvertently pulls in Spring Boot 2.3.0 when using the Gradle native BOM support

### ISSUE THREAD

**Issue by csabakos** [spring-cloud/spring-cloud-build#167]
**Describe the bug**
Hoxton.SR5 BOM inadvertently pulls in Spring Boot 2.3.0 when using the Gradle native BOM support (i.e. when *not* using the Spring Boot Gradle plugin).

[Link to gitter discussion](https://gitter.im/spring-cloud/spring-cloud?at=5ee3ba8c7c64f31f1158a5c4)

**Sample**
```
dependencies {
    compile platform("org.springframework.boot:spring-boot-dependencies:2.2.8.RELEASE")
    compile platform("org.springframework.cloud:spring-cloud-dependencies:Hoxton.SR5")
}
```
should result in Spring Boot 2.2.8 being brought in but it ends up brining in Spring Boot 2.3.0.

The older Hoxton.SR4 BOM does not have this issue.

(My Gradle version is 5.6.3 if it matters.)

**Comment by spencergibb** [comment]
Can you try with a later version of Gradle?

**Comment by csabakos** [comment]
@spencergibb I tried with gradle 6.4.1 but it did not resolve the issue.

This is the example `build.gradle` that I'm using:
```
plugins {
    id 'org.springframework.boot' version '2.2.8.RELEASE'
    id 'java'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '1.8'

repositories {
    mavenCentral()
}

dependencies {
    implementation platform("org.springframework.boot:spring-boot-dependencies:2.2.8.RELEASE")
    implementation platform("org.springframework.cloud:spring-cloud-dependencies:Hoxton.SR5")

    implementation 'org.springframework.cloud:spring-cloud-starter-sleuth'
    testImplementation('org.springframework.boot:spring-boot-starter-test') {
        exclude group: 'org.junit.vintage', module: 'junit-vintage-engine'
    }
}

test {
    useJUnitPlatform()
}
```

Doing a `./gradlew clean bootRun` will print the Spring Boot 2.3.0 banner.

**Comment by spencergibb** [comment]
It was really a shot in the dark.

**Comment by spencergibb** [comment]
Closing due to age of issue.
