### ISSUE TITLE
Root pom references multiple maven plugins with milestone versions

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-build#210]
Releaser now fails with milestone versions, but for 2020.0.2 build was released before that fix happened.

Either we need to change them or add a way so release can ignore those.

https://github.com/spring-cloud/spring-cloud-build/blob/6a702ea4441eb76faf9559198eae5e40f642737b/pom.xml#L69

and 

https://github.com/spring-cloud/spring-cloud-build/blob/6a702ea4441eb76faf9559198eae5e40f642737b/pom.xml#L75

**Comment by marcingrzejszczak** [comment]
I think that we should add some comment that would be checked in the same line. Sth like

```xml
<maven-surefire-report-plugin.version>3.0.0-M5</maven-surefire-report-plugin.version><!-- @releaser:off -->
```

**Comment by spencergibb** [comment]
yeah, the maven plugins don't matter.

**Comment by marcingrzejszczak** [comment]
Releaser code updated - https://github.com/spring-cloud/spring-cloud-release-tools/commit/4b6c8b375cd28ac992ebcd1dd23d9fb7ef8ee741
