### ISSUE TITLE
Update asciidoctorj version and fix deprecated constructor usage

### ISSUE THREAD

**Issue by DatChive** [spring-cloud/spring-cloud-build#212]
**Is your feature request related to a problem? Please describe.**

More recent versions of asciidoctorJ have deprecated a few constructors in favor of using builders.

**Describe the solution you'd like**

 I'm requesting an update to the asciidoctorJ version and subsequent constructor fixes.

**Describe alternatives you've considered**
N/A

**Additional context**

@jonatan-ivanov suggested we might want to update the spring-cloud-build since the original issue appeared in the spring-observability project, which used spring-cloud-build as a template.

[Original issue](https://github.com/spring-projects/spring-observability/issues/1)

**Comment by marcingrzejszczak** [comment]
done via https://github.com/spring-cloud/spring-cloud-build/pull/213
