### ISSUE TITLE
Default Spring Boot version in 3.0.x should move to 2.5.x

### ISSUE THREAD

**Issue by elefeint** [spring-cloud/spring-cloud-build#224]
Currently 3.0.x branch of spring-cloud-build [pulls in `spring-boot-dependencies` at version 2.4.13](https://github.com/spring-cloud/spring-cloud-build/blob/cc3685b5fff9bee508762f4dea42afd27ab0c48a/spring-cloud-build-dependencies/pom.xml#L17).

However,  Spring Boot 2.4.x [went out of support in November](https://spring.io/projects/spring-boot#support), so there likely won't be a 2.4.14. This is especially relevant given the log4j upgrade, which will be included in Spring Boot 2.5.8 but not in the 2.4.x branch.

Should Spring Cloud Build 3.0.x switch the Spring Boot version to 2.5.7 (and update to 2.5.8 when it comes out)?

A related question -- are you planning a 3.0.5 release after Spring Boot releases?

**Comment by spencergibb** [comment]
build 3.0.x supports both boot 2.4.x and 2.5.x. Uses don't get the spring boot version from spring cloud, so any log4j versions come with boot, not cloud.

**Comment by elefeint** [comment]
Got it; we should switch to managing Spring Boot version for building in Spring Cloud GCP directly, then. We still derived Spring Boot version from spring-cloud-dependencies for historical reasons.

Then it's just an FYI.

**Comment by spencergibb** [comment]
yes, that is a good idea since we may do things that may break you anyway.
