### ISSUE TITLE
Bug: Use Checkstyle file error

### ISSUE THREAD

**Issue by yuluo-yx** [spring-cloud/spring-cloud-build#240]
**Describe the bug**
I'm using the checkstyle configuration in the project to import Google's optional error incorrect import order,

**Sample**
1. I'm using the checkstyle configuration in the project to import Google's optional error incorrect import order,
2. I'm using the checkstyle configuration in the project to import Google's optional error incorrect import order,
    ```java
     import com.google.common.base.Optional;
     import com.netflix.loadbalancer.ILoadBalancer;
    ```

**result**
```
<error line="24" column="1" severity="error" message="非法导入： com.google.common.base.Optional 。" source="com.puppycrawl.tools.checkstyle.checks.imports.IllegalImportCheck"/>
</file>
```

**Comment by spencergibb** [comment]
I don't understand why this is a bug. This is for internal spring cloud projects

**Comment by yuluo-yx** [comment]
> I don't understand why this is a bug. This is for internal spring cloud projects

I don't understand. What do you mean?

**Comment by yuluo-yx** [comment]
> I don't understand why this is a bug. This is for internal spring cloud projects

What I mean is that I used the checkstyle configuration in the project in the spring cloud alibaba project. When I imported Google's optional api, he reported such an error? Spring cloud alibaba is not considered a spring cloud project?

**Comment by spencergibb** [comment]
spring-cloud-build is for projects under the spring-cloud GitHub org and not for general use. We specifically don't allow some Google projects and won't be changing it. I'd recommend using a custom patent pom since spring cloud Alibaba is not part of the spring cloud release train

**Comment by yuluo-yx** [comment]
> spring-cloud-build is for projects under the spring-cloud GitHub org and not for general use. We specifically don't allow some Google projects and won't be changing it. I'd recommend using a custom parent pom since spring cloud Alibaba is not part of the spring cloud release train

okay, got it.
