### ISSUE TITLE
What is the best practice to publish reference docs of Spring project

### ISSUE THREAD

**Issue by JoeWang1127** [spring-cloud/spring-cloud-build#243]
**Is your feature request related to a problem? Please describe.**
[ghpages.sh](https://github.com/spring-cloud/spring-cloud-build/blob/v4.0.5/docs/src/main/asciidoc/ghpages.sh) is marked as deprecated in spring-cloud-build v4.0.5
```
!!! WARNING !!!

THIS SCRIPT IS DEPRECATED!!
We're migrating away from using gh-pages at all. We're moving to using docs.spring.io and the zipped documentation.
Please migrate to the new approach as soon as possible since this script will be removed soon.

!!! WARNING !!!
```

What is the best practice of publishing reference docs for Spring project? Could you provide a sample or a how-to documentation?

**Describe the solution you'd like**
A sample or document describes how to publish Spring reference docs without `ghpages.sh`.

**Describe alternatives you've considered**
NA

**Additional context**
Our project, [spring-cloud-gcp](https://github.com/GoogleCloudPlatform/spring-cloud-gcp), uses spring-cloud-build to publish reference docs to [Github pages](https://pages.github.com/).

The `docs` module has a [ghpages.sh](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/main/docs/src/main/asciidoc/ghpages.sh) to convert `*.adoc` to `*.html` and commit the change to `gh-pages` branch and Github pages bot will pick up the docs and publish to `github.io`.

Since `ghpages.sh` is deprecated, we hope to know what's the best practise to publish docs moving forward.

**Comment by spencergibb** [comment]
We migrated to antora recently. We have not published to GitHub pages for a long time before that. I would not recommend depending on any build infrastructure here since it is subject to change without announcement.

I would copy ghpages to your local repo and customize as needed.
