### ISSUE TITLE
Add floating spring-pivotal JS footer to docs

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-build#28]
See http://docs.spring.io/spring-session/docs/1.2.0.BUILD-SNAPSHOT/reference/html5/

/cc @pieterhumphrey @bclozel @jacksoncvm

**Comment by spencergibb** [comment]
https://github.com/Pivotal-Web/docsearchbar via @trevormarshall

**Comment by pieterhumphrey** [comment]
request is to add the JS toolbar to all docs hung off cloud.spring.io

**Comment by spencergibb** [comment]
closing as docs are being redone
