### ISSUE TITLE
Why remove master branch?

### ISSUE THREAD

**Issue by SkyeBeFreeman** [spring-cloud/spring-cloud-build#328]
**Describe the bug**

Removing master branch makes my project cannot fetch checkstyle-suppressions.xml. [pom.xml](https://repo1.maven.org/maven2/org/springframework/cloud/spring-cloud-build/2.3.5.RELEASE/spring-cloud-build-2.3.5.RELEASE.pom)

<img width="1732" alt="image" src="https://github.com/user-attachments/assets/c5340a81-ae90-4c64-bfe2-9da234c36772">

Error log:
`
[ERROR] /Users/xxx/Code/github/spring-cloud-tencent/spring-cloud-starter-tencent-polaris-circuitbreaker/src/test/java/com/tencent/cloud/polaris/circuitbreaker/feign/PolarisCircuitBreakerFeignIntegrationDisableFeignHystrixTest.java:39: Line has leading space characters; indentation should be performed with tabs only. [RegexpSinglelineJava]
`

**Sample**
If possible, please provide a test case or sample application that reproduces
the problem. This makes it much easier for us to diagnose the problem and to verify that
we have fixed it.

**Comment by spencergibb** [comment]
We renamed it to main. This project is not meant for external users but for spring cloud projects
