### ISSUE TITLE
Use editor config for cross ide/editor formatting

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-build#33]
http://editorconfig.org/

Editor Config didn't use to support eclipse and it does now.

https://github.com/editorconfig/editorconfig/issues/108

@dsyer @marcingrzejszczak @adriancole @philwebb

**Comment by spencergibb** [comment]
Thanks to @mraible for the tip.

**Comment by philwebb** [comment]
Looks interesting but a little limited compared to [our checkstyle config](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-parent/src/checkstyle/checkstyle.xml).

**Comment by dsyer** [comment]
That was intentional (I hate the Fascist Boot bot).

**Comment by spencergibb** [comment]
The checkstyle config enforces formatting during build. Editor Config configures your editor rather than having to import the eclipse rules into intellij (which has flaws).

**Comment by spencergibb** [comment]
Moving to boot checkstyle (with exceptions) and spring formatter.
