### ISSUE TITLE
Upgrade maven-failsafe-plugin.version to the latest

### ISSUE THREAD

**Issue by wind57** [spring-cloud/spring-cloud-build#351]
My question is very trivial, but I fail to understand why.

How come, for example, the version for `maven-failsafe-plugin.version` is `2.22.2` while spring-boot-dependencies brings a much higher version. This means that all dependent projects (like spring-cloud-kubernetes) will use that lower version.

Thank you!

**Comment by spencergibb** [comment]
We don't inherit versions of plugins from spring boot

**Comment by spencergibb** [comment]
PRs welcome
