### ISSUE TITLE
Include plugin versions for javadoc and antrun in pluginManagement

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-build#40]
It looks like the commit

https://github.com/spring-cloud/spring-cloud-build/commit/61bd0522fdf2347f5aa15e054bbf2af1c8d5bbee

resulted in us not getting versions specified for javadoc and antrun plugins.  There are probably a couple other common ones that would be good to have as well. 

This was noticed as we got another older version for antrun and our .zip file for docs in dataflow was not being generated anymore...  See https://github.com/spring-cloud/spring-cloud-dataflow/commit/f9fca1a38b6b4a9d9be2366e1db60c5faf93803a

**Comment by spencergibb** [comment]
@markpollack are you going to do a PR?

**Comment by markpollack** [comment]
No.  I feel like I'm looking through a small peephole in terms of the effects of this change.   We also now have a lot of warning errors wrt to plugin versions in the build.  Trying to make it through a release and then hope to circle back again.

**Comment by dsyer** [comment]
Fixed in af055cf.
