### ISSUE TITLE
Problem updating to 1.0.0.RELEASE

### ISSUE THREAD

**Issue by jebeaudet** [spring-cloud/spring-cloud-build#5]
Hi!
I have some trouble updating to 1.0.0.RELEASE. I'm using my own parent pom and I'm explicitly declaring my `dependencyManagement` with `spring-cloud-starter-parent`. When updating, maven is having trouble finding the `spring-cloud-build` module which is not published on maven central. It works when I install the dependency locally as instructed on the wiki but I'd rather link on an official build. 

Also tried to add a `spring-cloud-build` dependency with version 1.0.0.RELEASE in my parent pom and adding the `https://oss.sonatype.org/service/local/staging/deploy/maven2` repository but from what I can see, the version is not published (yet?) on this repo.

I'm probably missing something obvious...

Thanks

**Comment by spencergibb** [comment]
Related https://github.com/spring-cloud/spring-cloud-build/issues/5

**Comment by jebeaudet** [comment]
Definitely a duplicate of spring-cloud/spring-cloud-netflix#244, sorry I didn't see it!

**Comment by spencergibb** [comment]
@jebeaudet will get deployed shortly, then sync to maven central.

**Comment by jebeaudet** [comment]
Good to hear thanks
