### ISSUE TITLE
Import order is incorrect

### ISSUE THREAD

**Issue by lly835** [spring-cloud/spring-cloud-build#66]
![jietu20180210-152425-hd](https://user-images.githubusercontent.com/2225913/36059648-3fc024e4-0e77-11e8-836b-02a788289d46.gif)

<img width="1260" alt="qq20180210-152714 2x" src="https://user-images.githubusercontent.com/2225913/36059657-53d2a88a-0e77-11e8-9627-a83cd3f35272.png">

IntelliJ IDEA 2017.2.5
Build #IU-172.4343.14, built on September 26, 2017
Subscription is active until April 9, 2018
For educational use only.
JRE: 1.8.0_152-release-915-b12 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6

I suggest giving a import order  file

**Comment by spencergibb** [comment]
See https://github.com/spring-cloud/spring-cloud-netflix/tree/master/eclipse

We should copy them here
