### ISSUE TITLE
Support checkstyle suppressions

### ISSUE THREAD

**Issue by dmitry-s** [spring-cloud/spring-cloud-build#78]
We have spring-boot applications in our project and `HideUtilityClassConstructorCheck` produces errors for them. We'd like to suppress these errors for those files, but it looks like you don't have `SuppressionFilter` enabled in your `checkstyle.xml`

What would you recommend?

**Comment by spencergibb** [comment]
I assume "we" means spring-cloud-gcp?

**Comment by dmitry-s** [comment]
Yes, exactly. Thanks.

**Comment by spencergibb** [comment]
PRs welcome. @marcingrzejszczak?
