### ISSUE TITLE
Consider using the maven flatten plugin for published POMs

### ISSUE THREAD

**Issue by snicoll** [spring-cloud/spring-cloud-build#89]
To avoid propagating build setup that is required to build a Spring Cloud project, the maven flatten plugin can be used. It has the advantage of letting you use whatever features you need while publishing "clean" pom to the repository.

We are using it in the Spring Boot project to remove repositories definitions.

**Comment by dsyer** [comment]
Fixed in  b4baf08 (should be in Greenwich and Hoxton snapshots).

**Comment by spencergibb** [comment]
reopening

**Comment by spencergibb** [comment]
Dave's attempt led to problems where spring cloud projects didn't have dependency management that is defined in this project (maven complaining about missing versions) and deployment being broken
```
Deployment failed: repository element was not specified in the POM inside distributionManagement element or in -DaltDeploymentRepository=id::layout::url parameter -
```

Maybe boot is different since it is all contained in the same project and doesn't need to depend on things deployed to repo.spring.io

I'm unsure how this will work in practice.

/cc @philwebb

**Comment by spencergibb** [comment]
Maybe it is only run with `central` profile?

**Comment by dsyer** [comment]
Hmm. I see the flaw in the plan. There’s probably no foolproof way to add this plugin to all cloud projects. One less perfect, but perhaps good enough, way would be to add it here in pluginManagement and then manually enable the plugin in every individual project (inheriting the configuration from here).

**Comment by spencergibb** [comment]
But in the end, won't repositories still end up in spring-cloud-build in that setup?

**Comment by dsyer** [comment]
Yes, but that’s not a pom that is used by end users (once it is scrubbed out by the flatten plugin).

**Comment by spencergibb** [comment]
How do we flatten spring-cloud-dependencies-parent without breaking all downstream projects?

**Comment by spencergibb** [comment]
I'll try this localy according to daves https://github.com/spring-cloud/spring-cloud-build/issues/89#issuecomment-472623407. The plugin can go in plugin management of build, but then it will need to be activated in each project.
